<a href="https://colab.research.google.com/github/sajidcsecu/PutorchTutorialYoutube/blob/main/PytorchTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
!pip list

Package                            Version
---------------------------------- ------------------
absl-py                            1.4.0
accelerate                         1.3.0
aiohappyeyeballs                   2.4.4
aiohttp                            3.11.12
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.23
albumentations                     2.0.3
ale-py                             0.10.1
altair                             5.5.0
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.6.0
arviz                              0.20.0
astropy                            7.0.0
astropy-iers-data                  0.2025.2.3.0.32.42
astunparse                         1.6.3
atpublic                           4.1.0
attrs                              25.1.0
audioread            

In [5]:
import numpy as np
import torch

# LISTs

In [6]:
my_list = [[1,2,3,4],[2,3,4,5]]
my_list

[[1, 2, 3, 4], [2, 3, 4, 5]]

# Numpy Array

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.43538816, 0.67892837, 0.91651209, 0.28812184],
       [0.2930764 , 0.92320206, 0.47094642, 0.85600391],
       [0.63796826, 0.82679983, 0.35603687, 0.70089759]])

In [9]:
np1.dtype

dtype('float64')

# Tensors

In [13]:
tensor_2d = torch.rand(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [12]:
# create a tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4354, 0.6789, 0.9165, 0.2881],
        [0.2931, 0.9232, 0.4709, 0.8560],
        [0.6380, 0.8268, 0.3560, 0.7009]], dtype=torch.float64)

In [14]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# reshape if you don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch2 = my_torch2.reshape(-1,2)
my_torch2


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
x = torch.arange(25).reshape(5,5)
print('Max:', x.shape, x.max())

Max: torch.Size([5, 5]) tensor(24)


In [22]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [24]:
x.max(dim=1)

torch.return_types.max(
values=tensor([ 4,  9, 14, 19, 24]),
indices=tensor([4, 4, 4, 4, 4]))

In [25]:
x = torch.randn(10,20,30)
z = x.permute(2,0,1) # np.permute()
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([10, 20, 30]) torch.Size([30, 10, 20])


In [26]:
x

tensor([[[-1.4085e+00, -3.4588e-01,  9.2482e-01,  ..., -7.6870e-01,
           8.2940e-01,  3.1151e-01],
         [ 6.8614e-01, -5.0096e-01, -2.8797e-02,  ...,  1.7152e+00,
          -1.6990e-01, -7.6623e-02],
         [-5.6108e-01, -1.1579e-01, -2.0793e-03,  ..., -2.6413e+00,
          -4.0518e-01, -7.9590e-01],
         ...,
         [ 1.4976e+00, -5.9592e-01, -1.3432e+00,  ..., -6.2352e-02,
          -2.4263e-02,  2.5023e+00],
         [-2.2266e+00, -7.3505e-01,  2.4111e+00,  ...,  2.3337e-01,
           1.8160e+00, -1.8350e+00],
         [-1.4251e+00, -1.6919e+00,  1.3159e-01,  ..., -5.0600e-01,
          -4.6024e-01, -3.6898e-02]],

        [[ 1.0958e+00, -7.6587e-01,  1.1665e+00,  ...,  7.3018e-01,
           1.4584e+00,  1.4152e+00],
         [ 7.2408e-01,  7.5769e-01, -4.1624e-01,  ...,  1.2922e+00,
           2.3178e-01,  1.6945e-01],
         [ 1.2267e+00, -1.5678e+00, -3.0736e-01,  ..., -8.6883e-01,
           3.6626e-01,  6.3191e-01],
         ...,
         [-2.6836e-01,  1

In [27]:
z

tensor([[[-1.4085e+00,  6.8614e-01, -5.6108e-01,  ...,  1.4976e+00,
          -2.2266e+00, -1.4251e+00],
         [ 1.0958e+00,  7.2408e-01,  1.2267e+00,  ..., -2.6836e-01,
           1.2438e+00, -5.5926e-01],
         [-9.8168e-01,  5.5347e-01,  1.6840e+00,  ...,  3.1437e-01,
          -5.9747e-01, -6.5797e-01],
         ...,
         [ 4.6331e-01,  4.7351e-01,  6.9540e-01,  ...,  1.6696e+00,
           2.3398e-01,  1.1892e-01],
         [-3.6300e-01, -3.4393e-03,  1.3630e+00,  ...,  4.4769e-03,
          -2.8223e-01,  1.3457e+00],
         [ 1.1337e+00, -4.0853e-01, -1.5574e+00,  ...,  9.3847e-01,
          -1.0904e+00,  8.6255e-01]],

        [[-3.4588e-01, -5.0096e-01, -1.1579e-01,  ..., -5.9592e-01,
          -7.3505e-01, -1.6919e+00],
         [-7.6587e-01,  7.5769e-01, -1.5678e+00,  ...,  1.8904e-02,
          -2.0817e+00, -9.6664e-01],
         [ 1.1034e+00, -1.6542e-01,  9.3690e-01,  ...,  1.0415e+00,
          -3.8978e-01, -4.9921e-01],
         ...,
         [ 4.2880e-01, -1

In [36]:
x = torch.tensor([[2., -1.], [1., 1.]], requires_grad=True)
print(x)

tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


In [37]:
out = x.pow(2).sum()

In [38]:
out

tensor(7., grad_fn=<SumBackward0>)

In [39]:
a = out.backward()

In [41]:
a

In [33]:
x.grad

tensor([[ 4., -2.],
        [ 2.,  2.]])

In [1]:
import torch
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]

In [2]:
x

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [3]:
y

[[3], [7], [11], [15]]

In [4]:
X = torch.tensor(x).float()
Y = torch.tensor(y).float()

In [5]:
X

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [6]:
Y

tensor([[ 3.],
        [ 7.],
        [11.],
        [15.]])

In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
X = X.to(device)
Y = Y.to(device)

In [8]:
X

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [9]:
import torch.nn as nn
class MyNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_to_hidden_layer = nn.Linear(2,8)
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Linear(8,1)

    def forward(self, x):
      x = self.input_to_hidden_layer(x)
      x = self.hidden_layer_activation(x)
      x = self.hidden_to_output_layer(x)
      return x

In [11]:
mynet = MyNeuralNet().to(device)

In [12]:
mynet.input_to_hidden_layer.weight

Parameter containing:
tensor([[-0.5285, -0.1149],
        [ 0.1551,  0.4783],
        [-0.1068,  0.6300],
        [-0.6756, -0.1270],
        [ 0.2432,  0.1765],
        [-0.6583,  0.6584],
        [-0.4481,  0.2461],
        [-0.1703,  0.2005]], requires_grad=True)

In [13]:
mynet.parameters()

<generator object Module.parameters at 0x7db42196fca0>

In [15]:
for par in mynet.parameters():
  print(par)

Parameter containing:
tensor([[-0.5285, -0.1149],
        [ 0.1551,  0.4783],
        [-0.1068,  0.6300],
        [-0.6756, -0.1270],
        [ 0.2432,  0.1765],
        [-0.6583,  0.6584],
        [-0.4481,  0.2461],
        [-0.1703,  0.2005]], requires_grad=True)
Parameter containing:
tensor([-0.3419, -0.4500, -0.1104, -0.5656,  0.6405,  0.0804,  0.4908, -0.3295],
       requires_grad=True)
Parameter containing:
tensor([[-0.1373,  0.2493,  0.2902, -0.2769, -0.3147,  0.1500,  0.1478, -0.3476]],
       requires_grad=True)
Parameter containing:
tensor([-0.0220], requires_grad=True)


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

class Model(nn.Module):
  def __init__(self,in_features =4, h1=8, h2=9, out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(in_features,h1)
    self.fc2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2,out_features)

  def forward(self,x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)
    return x


In [2]:
torch.manual_seed(41)
model=Model()

In [3]:
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
my_df = pd.read_csv(url)

In [4]:
my_df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
my_df["species"] = my_df["species"].replace({"setosa":0.0, "versicolor":1.0, "virginica":2.0})

<ipython-input-5-f71b77886b70>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  my_df["species"] = my_df["species"].replace({"setosa":0.0, "versicolor":1.0, "virginica":2.0})


In [6]:
my_df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [7]:
# Train Test Split Set (X,Y)
X = my_df.drop("species", axis=1)
y = my_df["species"]

In [8]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [9]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: species, Length: 150, dtype: float64

In [10]:
# convert these to numpy
X= X.values
y= y.values

In [13]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
# Train Test Split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=41)

In [15]:
# Convert X features to float tensors
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)


In [16]:
# Convert Y labels to tensors long
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [17]:
# set the criterion of model to measure the error, how far off the predictions of data
criterion = nn.CrossEntropyLoss()
# choose adam optimizer, lr = learning rate (if error doesn't go down after a bunch of iterations (epochs), lower learning rate )
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [18]:
# Train the model
# epochs? one run through all the training data in our network
epochs = 100
losses = []
for i in range (epochs):
  # go forward and get a prediction
  y_pred = model.forward(X_train) # get a predicted results
  # Measure the loss/error, gonna be a high at first
  loss = criterion(y_pred,y_train)
  # keep the track of our losses
  losses.append(loss.detach().numpy())
  # print every 10 epoch
  if i%10==0:
    print(f"Epoch : {i} and Loss : {loss}")

  # do some back propagation : take the error rate of forward propagation and feed it back
  # through the network to fine tune the weights
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()


Epoch : 0 and Loss : 1.1251550912857056
Epoch : 10 and Loss : 1.0096259117126465
Epoch : 20 and Loss : 0.8157405853271484
Epoch : 30 and Loss : 0.585706353187561
Epoch : 40 and Loss : 0.3999636471271515
Epoch : 50 and Loss : 0.26768800616264343
Epoch : 60 and Loss : 0.17942364513874054
Epoch : 70 and Loss : 0.12151692062616348
Epoch : 80 and Loss : 0.0860118493437767
Epoch : 90 and Loss : 0.06520849466323853


In [19]:
# Evaluate the data on the test dataset
with torch.no_grad(): # turn off back propagation
  y_eval = model.forward(X_test)
  loss = criterion(y_eval,y_test)

In [20]:
loss

tensor(0.1315)

In [26]:
correct =0
with torch.no_grad(): # turn off back propagation
  for i,data in enumerate(X_test):
    y_eval = model.forward(data)
    print(f"{i+1}.) {str(y_eval)} \t {y_test[i]} \t {y_eval.argmax().item()}")
    #correct or not
    if y_eval.argmax().item() == y_test[i]:
      correct+=1
print(f"{correct} out of {len(y_test)} = {100*correct/len(y_test)}%")


1.) tensor([-5.8760,  4.4628,  6.5124]) 	 2 	 2
2.) tensor([-7.5436,  4.1670,  9.7255]) 	 2 	 2
3.) tensor([-8.4504,  5.1271, 10.1987]) 	 2 	 2
4.) tensor([-4.3398,  5.6267,  2.5608]) 	 1 	 1
5.) tensor([-7.1825,  4.8754,  8.2992]) 	 2 	 2
6.) tensor([-3.3974,  5.3463,  1.2803]) 	 1 	 1
7.) tensor([-5.9231,  4.9822,  5.9997]) 	 2 	 2
8.) tensor([-4.2881,  5.7003,  2.3889]) 	 1 	 1
9.) tensor([-6.5356,  4.9257,  7.1260]) 	 2 	 2
10.) tensor([-8.0509,  4.4129, 10.3286]) 	 2 	 2
11.) tensor([-5.6762,  4.9500,  5.6215]) 	 2 	 2
12.) tensor([ 4.5662, -2.2476, -2.8911]) 	 0 	 0
13.) tensor([ 4.2571, -1.9967, -2.7330]) 	 0 	 0
14.) tensor([-2.1108,  4.0515,  0.5799]) 	 1 	 1
15.) tensor([ 3.4575, -1.2098, -2.3514]) 	 0 	 0
16.) tensor([-5.4724,  5.1165,  5.0934]) 	 2 	 1
17.) tensor([ 4.0557, -1.7949, -2.6492]) 	 0 	 0
18.) tensor([-5.8075,  4.6053,  6.2458]) 	 1 	 2
19.) tensor([ 4.4343, -2.1392, -2.8242]) 	 0 	 0
20.) tensor([ 3.4527, -1.2514, -2.3660]) 	 0 	 0
21.) tensor([-2.6189,  4.5619

In [27]:
# save our NN Model
torch.save(model.state_dict(),"iris_model.pt")

In [29]:
# load the saved model
new_model = Model()
new_model.load_state_dict(torch.load("iris_model.pt"))

<ipython-input-29-54d0345b7be8>:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  new_model.load_state_dict(torch.load("iris_model.pt"))


<All keys matched successfully>

In [31]:
# make sure it loaded correctly
new_model.eval()

Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)

# CNN experiment on MNIST

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import make_grid
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [2]:
# convert MNIST image files into a Tensor of 4 dimension (number of images, height, width, number of channel)
transform = transforms.ToTensor()

In [3]:
# Train Data
train_data = datasets.MNIST(root="/cnn_data",train=True,download=True,transform=transform)

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 9.91M/9.91M [00:00<00:00, 16.0MB/s]


Extracting /cnn_data/MNIST/raw/train-images-idx3-ubyte.gz to /cnn_data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 28.9k/28.9k [00:00<00:00, 493kB/s]


Extracting /cnn_data/MNIST/raw/train-labels-idx1-ubyte.gz to /cnn_data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 1.65M/1.65M [00:00<00:00, 4.45MB/s]


Extracting /cnn_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /cnn_data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 4.54k/4.54k [00:00<00:00, 3.46MB/s]

Extracting /cnn_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /cnn_data/MNIST/raw



In [4]:
# test data
test_data = datasets.MNIST(root="/cnn_data",train=False,download=True,transform=transform)

In [5]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: /cnn_data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [6]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: /cnn_data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [7]:
pwd

'/content'

In [8]:
ls

sample_data/


In [9]:
cd ../

/


In [10]:
ls

bin@                        datalab/  lib32@   NGC-DL-CONTAINER-LICENSE  root/  tmp/
boot/                       dev/      lib64@   opt/                      run/   tools/
cnn_data/                   etc/      libx32@  proc/                     sbin@  usr/
content/                    home/     media/   python-apt/               srv/   var/
cuda-keyring_1.1-1_all.deb  lib@      mnt/     python-apt.tar.xz*        sys/


In [11]:
cd cnn_data

/cnn_data


In [12]:
ls

MNIST/


In [13]:
cd content

[Errno 2] No such file or directory: 'content'
/cnn_data


In [14]:
cd ..

/


In [15]:
cd content

/content


In [16]:
pwd

'/content'

In [17]:
# create a small batch of image... let say it is 10
train_loader = DataLoader(train_data,batch_size=10,shuffle=True)
test_loader = DataLoader(test_data,batch_size=10,shuffle=False)


In [28]:
# define the CNN model (2 layer)
conv1 = nn.Conv2d(1,6,3,1)
conv2 = nn.Conv2d(6,6,3,1)

In [29]:
# grib 1 MNIST record/image
for i,(X_Train,y_train) in enumerate(train_data):
  break

In [30]:
X_Train.shape

torch.Size([1, 28, 28])

In [31]:
x = X_Train.view(1,1,28,28)

In [32]:
x.shape

torch.Size([1, 1, 28, 28])

In [33]:
# perform our first convolution
x = F.relu(conv1(x))

In [34]:
x.shape

torch.Size([1, 6, 26, 26])

In [35]:
# pass through the pooling layer
x= F.max_pool2d(x,2,2)

In [36]:
x.shape

torch.Size([1, 6, 13, 13])

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import make_grid
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt


class Mycnn(nn.Module):
  def __init__(self):
    super().__init__()
    # cnn layer
    self.conv1 = nn.Conv2d(1,6,3,1)
    self.conv2 = nn.Conv2d(6,16,3,1)
    # fully connected layer
    self.fc1 = nn.Linear(5*5*16,120)
    self.fc2 = nn.Linear(120,84)
    self.fc3 = nn.Linear(84,10)

  def forward(self,x):
    # first pass
    x = F.relu(self.conv1(x))
    x = F.max_pool2d(x,2,2)
    # second pass
    x = F.relu(self.conv2(x))
    x = F.max_pool2d(x,2,2)
    # Review to flatten the it out
    x = x.view(-1,16*5*5) # negative 1 so that we can vary the batch size
    # fully connected layers
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return F.log_softmax(x,dim=1)

In [20]:
# create an instance of Model
torch.manual_seed(41)
model = Mycnn()
model

Mycnn(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [21]:
# loss Function Optimizer
loss = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [22]:
# convert MNIST image files into a Tensor of 4 dimension (number of images, height, width, number of channel)
transform = transforms.ToTensor()
# Train Data
train_data = datasets.MNIST(root="/cnn_data",train=True,download=True,transform=transform)
# test data
test_data = datasets.MNIST(root="/cnn_data",train=False,download=True,transform=transform)

In [23]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: /cnn_data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [24]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: /cnn_data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [25]:
# create a small batch of image... let say it is 10
train_loader = DataLoader(train_data,batch_size=10,shuffle=True)
test_loader = DataLoader(test_data,batch_size=10,shuffle=False)

In [26]:
train_loader

In [27]:
# set the criterion of model to measure the error, how far off the predictions of data
criterion = nn.CrossEntropyLoss()
# choose adam optimizer, lr = learning rate (if error doesn't go down after a bunch of iterations (epochs), lower learning rate )
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [28]:
import time
start_time = time.time()

# Create variables to track things
epochs = 5
train_losses = []
test_losses = []
train_correct = []
test_correct = []

# For loop of epochs
for i in range(epochs):
  trn_corr = 0
  tst_corr = 0

  # Train
  for b, (X_train, y_train) in enumerate(train_loader):
    b+=1 # start batches at 1
    y_pred = model(X_train)
    loss = criterion(y_pred, y_train)
    predicted = torch.max(y_pred.data, 1)[1] # add up the number of correct predictions. Indexed off the first point
    batch_corr = (predicted == y_train).sum() # how many we got correct from the specific batch
    trn_corr += batch_corr # keep track as we go along in training
    # update our parameters
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    # print the results
    if b%600 == 0:
      print(f'epoch: {i}  batch: {b}  loss: {loss.item()}  \accuracy: {trn_corr.item()*100/(10*b)}')

  train_losses.append(loss)
  train_correct.append(trn_corr)

  # Test
  with torch.no_grad():
    for b, (X_test, y_test) in enumerate(test_loader):
      y_val = model(X_test)
      predicted = torch.max(y_val.data, 1)[1]
      tst_corr += (predicted == y_test).sum()

    loss = criterion(y_val, y_test)
    test_losses.append(loss)
    test_correct.append(tst_corr)


current_time = time.time()
total_time = current_time - start_time
print(f"Time taken : {total_time/60} minutes")

epoch: 0  batch: 600  loss: 0.01122160442173481  ccuracy: 79.26666666666667
epoch: 0  batch: 1200  loss: 0.5097795128822327  ccuracy: 85.6
epoch: 0  batch: 1800  loss: 0.27345114946365356  ccuracy: 88.16666666666667
epoch: 0  batch: 2400  loss: 0.5706523656845093  ccuracy: 89.49583333333334
epoch: 0  batch: 3000  loss: 0.010505528189241886  ccuracy: 90.20666666666666
epoch: 0  batch: 3600  loss: 0.1338011920452118  ccuracy: 90.83888888888889
epoch: 0  batch: 4200  loss: 0.0005176571430638433  ccuracy: 91.27380952380952
epoch: 0  batch: 4800  loss: 0.10394303500652313  ccuracy: 91.65208333333334
epoch: 0  batch: 5400  loss: 0.2622598111629486  ccuracy: 91.98333333333333
epoch: 0  batch: 6000  loss: 0.0009407080942764878  ccuracy: 92.145
epoch: 1  batch: 600  loss: 0.010575367137789726  ccuracy: 94.61666666666666
epoch: 1  batch: 1200  loss: 0.004694225732237101  ccuracy: 94.75
epoch: 1  batch: 1800  loss: 0.06041830778121948  ccuracy: 94.82222222222222
epoch: 1  batch: 2400